# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.2.2
maven_group = mc.smpessentials
archives_name = quackedsmp
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# NeoForm (for common module - ModDevGradle)
neoform_version = 26.1.2-1

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.147.0+26.1.2
neoforge_version = 26.1.2.29-beta
mixin_extras = 0.5.4
