{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoform",
    "version": "1.21.8-20250717.133445",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "neoformData",
      "attributes": {
        "org.gradle.jvm.version": 21
      },
      "dependencies": [
        {
          "group": "org.vineflower",
          "module": "vineflower",
          "version": {
            "requires": "1.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "fatjar"
            }
          }
        },
        {
          "group": "net.neoforged",
          "module": "AutoRenamingTool",
          "version": {
            "requires": "2.0.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "AutoRenamingTool",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "installertools",
          "version": {
            "requires": "2.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "installertools",
              "type": "jar",
              "extension": "jar",
              "classifier": "fatjar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "neoform-1.21.8-20250717.133445.zip",
          "url": "neoform-1.21.8-20250717.133445.zip",
          "size": 1928033,
          "sha512": "3d3000b18640d39b98a5a3f14d60bd315c85029673c0128975a386322ee89b8f8c62a0b984f502723e096a1b2cc2132c9721e55b341cfbb2643c4845ae6f1c26",
          "sha256": "d67401bd0769ee045128fb84142fb660fe49db8ea86538d4dc308c25cd0cdbca",
          "sha1": "1b2bb7418b0ccf190086a28c8b78f94acca7e1b1",
          "md5": "6201a0f31d4a0febe75db7521f402682"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform",
          "version": "1.21.8-20250717.133445"
        }
      ]
    },
    {
      "name": "neoformRuntimeElements",
      "attributes": {
        "org.gradle.jvm.version": 21,
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "minecraft-dependencies",
          "version": {
            "requires": "1.21.8"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform-dependencies",
          "version": "1.21.8-20250717.133445"
        }
      ]
    },
    {
      "name": "neoformApiElements",
      "attributes": {
        "org.gradle.jvm.version": 21,
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "ca.weblite",
          "module": "java-objc-bridge",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "net.neoforged",
          "module": "minecraft-dependencies",
          "version": {
            "requires": "1.21.8"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoform-dependencies",
          "version": "1.21.8-20250717.133445"
        }
      ]
    }
  ]
}
