modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "quacksmp"
version = "${version}"
displayName = "QuackSMP"
authors = "Rvhoyos"
description = '''
Comprehensive server-side utility mod featuring claims, RPG skills, and chat management for 1.21.8.
'''
issueTrackerURL = "https://github.com/Rvhoyos/QuackedSMP/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/quackedsmp"
logoFile = "assets/quacksmp/icon.png"
#logoFile = ""

[[dependencies.quacksmp]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quacksmp]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "quacksmp.mixins.json"
