modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "quacksmp"
version = "${version}"
displayName = "QuackSMP"
authors = "Monte_Carlo_Simulations"
description = '''
Server-side mod with a built-in browser admin panel. Every feature is modular, enable only what you want. Includes claims, RPG skills, custom dimensions, chat filter, Discord, Votifier, and more. No config editing required.
'''
issueTrackerURL = "https://github.com/Rvhoyos/QuackedSMP/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/quackedsmp"
logoFile = "assets/quacksmp/icon.png"
#logoFile = ""

[[dependencies.quacksmp]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quacksmp]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "quacksmp.mixins.json"

[[mixins]]
config = "quacksmp-neoforge.mixins.json"
