plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    version = rootProject.neoforge_version

    parchment.minecraftVersion = rootProject.parchment_mc_version
    parchment.mappingsVersion = rootProject.parchment_version

    runs {
        client {
            client()
            programArguments.addAll '--username', "Player${new Random().nextInt(10000)}"
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        quacksmp {
            sourceSet project.sourceSets.main
        }
    }
}

dependencies {
    // Common module
    compileOnly project(':common')

    // Optional BlueMap Integration
    compileOnly "de.bluecolored:bluemap-api:2.7.3"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: inputs.properties.version
    }
}
