{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "neoforge",
    "version": "21.8.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.8.33-sources.jar",
          "url": "neoforge-21.8.33-sources.jar",
          "size": 1894655,
          "sha512": "3e80288b4e2e41b5bd39e209ea0124cb7d3b9346426fe941e213844e8dd4d1bf9f7c1724e098b4d4fdaa3aa81e22d17d572f78b7d6a3cc73b0233ca3a0c4c1d4",
          "sha256": "2bd916cf0d22e4fcf7c7acd2970100dd7e9567921f41372310811391a1f64aaa",
          "sha1": "a55212fbec4e8c33690ee2b3a6d04fbe5203ce7b",
          "md5": "0c2f0a6438ad63f82996ab19ba76767d"
        }
      ]
    },
    {
      "name": "modDevBundle",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.8-20250717.133445"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "neoforge-21.8.33-userdev.jar",
          "url": "neoforge-21.8.33-userdev.jar",
          "size": 4018198,
          "sha512": "3c4063ecc8f91ebc69311d22d477f79b6a82ee7b0b22573492a0b2aa4a62f5b32fff7f25eb44dfaa8d35c92895e5da74facd4314d5ff9d580869c1cf922dbc14",
          "sha256": "087de663646681917830813cb4e92bca83f623a3c3cb1954c23a20ed8cdb0d73",
          "sha1": "f9ab325c0c5927f1d12cd21a71a2f8ff7f04554c",
          "md5": "cbc0f7a1f13966891170a6dca47f45d2"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-bundle",
          "version": "21.8.33"
        }
      ]
    },
    {
      "name": "modDevConfig",
      "attributes": {
        "org.gradle.category": "data",
        "org.gradle.dependency.bundling": "external"
      },
      "files": [
        {
          "name": "neoforge-21.8.33-moddev-config.json",
          "url": "neoforge-21.8.33-moddev-config.json",
          "size": 11049,
          "sha512": "cf549344bd8bf020efd8c00a0e5c6edc4cfdb0be06bb05694bff3c255b55abf26fabf319f5ae3348d2b3fb0de3d7db1b8b88ebde32daddf1aa047deb7fd48c11",
          "sha256": "8b8972e6a714c12b13352c1782549c7a79e4341ae50004fa2ea16a022b76c2d5",
          "sha1": "c54625d12f6a1d45e1a7a298f0101bc3bb83dd14",
          "md5": "d0815b1826427d38d14e6ce345274c1f"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-config",
          "version": "21.8.33"
        }
      ]
    },
    {
      "name": "installerJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "embedded",
        "org.gradle.jvm.version": 8,
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.8.33-installer.jar",
          "url": "neoforge-21.8.33-installer.jar",
          "size": 6159345,
          "sha512": "1f308cbe19a743e257ba9e0aed390f3d057a7262372688358c2bec930bdd807d6228a6023f16006cf6fc3b59d20b2667861c9da6af3dd04b5fdff86e9fdbbabd",
          "sha256": "cead9a305ba54f7d8fa903e5ff37111a12167102c4b2ac7ddba3d63487a6b77d",
          "sha1": "ff650f856c432db20ebabcfb30d289de1b717c47",
          "md5": "f1d7f6f10f526f002c0d857b80a7e75a"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-installer",
          "version": "21.8.33"
        }
      ]
    },
    {
      "name": "universalJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neoforge-21.8.33-universal.jar",
          "url": "neoforge-21.8.33-universal.jar",
          "size": 3632723,
          "sha512": "d749f54e6d8b35310fb9d7a2eaf1fadf6b5be25c5613dc718d1eb7bb2886cc03d5d8b6de1c7c2317a0c3991b0856233fafec7109fa9cc52114f9ab8423ab28e4",
          "sha256": "9daffe99bfe33ee0cdccb5e1f804f73a4e42a7d4e4920c4484a6d59960a02b05",
          "sha1": "4bd097b1456c51909d3234ae171530a87f61e4a7",
          "md5": "0df0e86b76d1c7ddf5d1b7c22e5726b1"
        }
      ]
    },
    {
      "name": "changelog",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "changelog"
      },
      "files": [
        {
          "name": "neoforge-21.8.33-changelog.txt",
          "url": "neoforge-21.8.33-changelog.txt",
          "size": 7922,
          "sha512": "5a47fc44d1a4f29c7677d78a101cd630deacb125304837e6ed0dc09decf4af18924a99bfbc414b7378787c70a4b9160b6c80fa1d336caff3dd3105e1b5476dc1",
          "sha256": "2ad8d89a884c3c33bbcd3fd59b1855b7d3615bed25dd3f89476010c088a62278",
          "sha1": "458279db75e8384a5eae5591086c313e915ad370",
          "md5": "10595d7beb55d20cf446d6135ffd7d5e"
        }
      ]
    },
    {
      "name": "modDevApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "9.0.16"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "9.0.16"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.15.2+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "securejarhandler",
          "version": {
            "requires": "9.0.16"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "bootstraplauncher",
          "version": {
            "requires": "9.0.16"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.8-20250717.133445"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "21.8.33"
        }
      ]
    },
    {
      "name": "modDevRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "strictly": "9.8",
            "requires": "9.8"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "loader",
          "version": {
            "requires": "9.0.16"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "earlydisplay",
          "version": {
            "requires": "9.0.16"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            },
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "accesstransformers",
          "version": {
            "requires": "11.0.2"
          }
        },
        {
          "group": "net.neoforged",
          "module": "bus",
          "version": {
            "requires": "8.0.5"
          }
        },
        {
          "group": "net.neoforged",
          "module": "mergetool",
          "version": {
            "requires": "2.0.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "mergetool",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.8.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.9"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "net.minecrell",
          "module": "terminalconsoleappender",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "sponge-mixin",
          "version": {
            "requires": "0.15.2+mixin.0.8.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "securejarhandler",
          "version": {
            "requires": "9.0.16"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "bootstraplauncher",
          "version": {
            "requires": "9.0.16"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "net.neoforged",
          "module": "neoform",
          "version": {
            "requires": "1.21.8-20250717.133445"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "neoform-dependencies"
            }
          ],
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-dependencies",
          "version": "21.8.33"
        }
      ]
    },
    {
      "name": "modDevModulePath",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "securejarhandler",
          "version": {
            "requires": "9.0.16"
          }
        },
        {
          "group": "net.neoforged.fancymodloader",
          "module": "bootstraplauncher",
          "version": {
            "requires": "9.0.16"
          }
        },
        {
          "group": "net.neoforged",
          "module": "JarJarFileSystems",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-module-path",
          "version": "21.8.33"
        }
      ]
    },
    {
      "name": "modDevTestFixtures",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged.fancymodloader",
          "module": "junit-fml",
          "version": {
            "requires": "9.0.16"
          },
          "endorseStrictVersions": true
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "neoforge-moddev-test-fixtures",
          "version": "21.8.33"
        }
      ]
    }
  ]
}
